name: Elixir Unit Test
inputs:
  elixir-version:
    required: true
    type: string
  erlang-version:
    required: true
    type: string
  github-repository:
    description: 'Optionally specify the repository against which to authenticate. Must be included if the `github-token` option is used.'
    required: false
    default: 'false'
    type: string
  app-installation-id:
    description: 'Optionally rewrite all GitHub URLs to authenticate with an app-generated token.'
    required: false
    default: 'false'
    type: string
  app-installation-key:
    description: 'Optionally rewrite all GitHub URLs to authenticate with an app-generated token.'
    required: false
    default: 'false'
    type: string
# using a string because booleans currently converted to strings
# within workflow dispatches and composite actions
# https://github.com/actions/runner/issues/1483
  skip-checkout:
    required: false
    default: 'false'
    type: string
runs:
  using: composite
  steps:
    - uses: rentpath/actions-services-elixir-deps@v1.6.4
      with:
        elixir-version: ${{ inputs.elixir-version }}
        erlang-version: ${{ inputs.erlang-version }}
        github-repository: ${{ inputs.github-repository }}
        app-installation-id: ${{ inputs.app-installation-id }}
        app-installation-key: ${{ inputs.app-installation-key }}
        mix-env: test
        skip-checkout: ${{ inputs.skip-checkout }}
    - name: Unit Test
      env:
        MIX_ENV: test
      run: mix do compile --force, credo --strict, test, clean
      shell: bash
